import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

const url=process.env.SUPABASE_TEST_URL; const anon=process.env.SUPABASE_TEST_ANON_KEY; const service=process.env.SUPABASE_TEST_SERVICE_ROLE_KEY;
const enabled=Boolean(url&&anon&&service);
let admin:SupabaseClient; let userA:SupabaseClient; let userB:SupabaseClient; let userAId=""; let userBId=""; let planId="";
const password="RlsTest123!";
const plan={schemaVersion:1,title:"RLS rice plan",region:{provinceCode:"32",regencyCode:"32.04",districtCode:null},cropPlan:{cropType:"rice",templateVersion:"test-v1",plantingDate:"2026-07-01",estimatedHarvestDate:"2026-10-20",cycleDurationDays:112,productionPhases:[],expectedHarvestQuantity:3000,quantityUnit:"kg",expectedSellingPriceRupiah:6500,assumptions:[]},cashFlowItems:[{type:"income",category:"harvest",amountRupiah:19500000,timingDate:"2026-10-20",isHarvestIncome:true}],monthlyHouseholdExpenseRupiah:1000000,openingBalanceRupiah:1000000,emergencyReserveRupiah:500000,financingOptions:[{name:"Bullet",principalRupiah:12000000,interestRateBps:1200,interestPeriod:"ANNUAL",administrationFeeRupiah:100000,otherUpfrontFeesRupiah:0,financingStartDate:"2026-07-01",gracePeriodMonths:0,numberOfInstallments:1,repaymentFrequency:"ONCE",repaymentStructure:"BULLET",firstRepaymentDate:"2026-11-15"}]};

describe.skipIf(!enabled)("live Supabase RLS",()=>{
  beforeAll(async()=>{ admin=createClient(url!,service!,{auth:{persistSession:false}}); const stamp=Date.now(); const a=await admin.auth.admin.createUser({email:`rls-a-${stamp}@example.test`,password,email_confirm:true}); const b=await admin.auth.admin.createUser({email:`rls-b-${stamp}@example.test`,password,email_confirm:true}); userAId=a.data.user!.id; userBId=b.data.user!.id; const sa=await createClient(url!,anon!,{auth:{persistSession:false}}).auth.signInWithPassword({email:a.data.user!.email!,password}); const sb=await createClient(url!,anon!,{auth:{persistSession:false}}).auth.signInWithPassword({email:b.data.user!.email!,password}); userA=createClient(url!,anon!,{global:{headers:{Authorization:`Bearer ${sa.data.session!.access_token}`}},auth:{persistSession:false}}); userB=createClient(url!,anon!,{global:{headers:{Authorization:`Bearer ${sb.data.session!.access_token}`}},auth:{persistSession:false}}); const created=await userA.rpc("create_plan",{p_plan:plan,p_source:"new"}); expect(created.error).toBeNull(); planId=created.data.id; },30000);
  afterAll(async()=>{ if(planId) await admin.from("plans").delete().eq("id",planId); if(userAId) await admin.auth.admin.deleteUser(userAId); if(userBId) await admin.auth.admin.deleteUser(userBId); });
  it("allows the owner to read the plan",async()=>{const result=await userA.rpc("get_plan",{p_plan_id:planId}); expect(result.error).toBeNull(); expect(result.data.id).toBe(planId);});
  it("hides the plan from another user",async()=>{const direct=await userB.from("plans").select("id").eq("id",planId); expect(direct.error).toBeNull(); expect(direct.data).toEqual([]); const rpc=await userB.rpc("get_plan",{p_plan_id:planId}); expect(rpc.error).toBeNull(); expect(rpc.data).toBeNull();});
  it("prevents another user from updating it",async()=>{const result=await userB.from("plans").update({title:"stolen"}).eq("id",planId).select(); expect(result.error).toBeNull(); expect(result.data).toEqual([]);});
});